drm: Declare missing prototypes in <drm/drm_mipi_dsi.h> [FreeBSD]
... and probably more than we need.

This fixes dozens of warnings of the following form when compiling
`drm_mipi_dsi.c`:

    error: no previous prototype for function '...'

Sponsored by:	The FreeBSD Foundation